version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - pip install -r src/requirements.txt
  build:
    commands:
      - python src/shortterm_topstock_select.py

artifacts:
  files:
    - '**/*'
  discard-paths: yes
